name: CI/CD
on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  CD:
    runs-on: dmz-bobby
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: start service
        run: |
          cd docker
          docker compose up -d