name: CI/CD
on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**.md'
      - '.github/workflows/**'
  workflow_dispatch:


jobs:
  CD:
    runs-on: nhvilhelmsen
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: start service
        run: |
          cd docker
          docker compose down
          docker compose up -d